variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'frontendregulatoraccountenrollment'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'frontendregulatoraccountenrollment'
  serviceName: 'prdrwdwebwa1414'
